# Generated by Django 2.0.7 on 2019-03-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('view_article', '看文章的权限!')]},
        ),
    ]
