# Generated by Django 2.0.7 on 2019-03-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='remove',
            field=models.NullBooleanField(),
        ),
    ]
