# Generated by Django 2.0.7 on 2019-03-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='signature',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
