# Generated by Django 2.0.7 on 2019-03-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_person_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
