# Generated by Django 2.0.7 on 2019-03-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
