# Generated by Django 2.0.7 on 2019-03-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_bookorder_create_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookorder',
            options={'ordering': ['-create_time', 'price']},
        ),
    ]
